# Generated by Django 4.1.5 on 2023-01-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField(max_length=50)),
                ('comment', models.TextField()),
                ('files', models.FileField(blank=True, null=True, upload_to='Files')),
            ],
        ),
    ]
